# Add 'beta' label to any PR where the base branch name starts with `beta`
beta:
  - base-branch: ['^beta', 'beta', 'beta*']

# Add 'alpha' label to any PR where the base branch name starts with `alpha`
alpha:
  - base-branch: ['^alpha', 'alpha', 'alpha*']

# Add 'latest' label to any PR where the base branch name starts with `latest`
latest:
  - base-branch: ['^latest', 'latest', 'latest*']

# Add labels based on head branch name patterns
feature:
  - head-branch: ['^feature/']

fix:
  - head-branch: ['^fix/']

chore:
  - head-branch: ['^chore/']
