changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: Featured Changes ✨
      labels:
        - feature
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - fix
        - bugfix
        - bug
    - title: Maintenance Tasks 🧰
      labels:
        - chore
        - housekeeping
        - '*'
