name: fastybird_smart_app
repository: https://github.com/FastyBird/smart-panel

packages:
  - apps/*

scripts:
  analyze:
    run: |
      # Ensure generated API/spec files exist before analysis
      melos run rebuild-api
      melos run rebuild-spec
      melos exec -- "dart analyze ."

  generate-run-config:
    run: bash ./bin/generate_app_run_config.sh

  rebuild-all:
    run: melos rebuild-api && melos rebuild-spec
    description: Rebuilds both the OpenAPI-generated API and the static spec files.

  rebuild-api:
    run: |
      echo "🧼 Cleaning API directory..." && \
      cd ./apps/panel/ && \
      rm -rf lib/api && \
      dart run swagger_parser && \
      dart run build_runner build
    description: Cleans the API directory, regenerates interfaces, and runs build_runner.

  rebuild-spec:
    run: |
      echo "🧼 Cleaning spec directory..." && \
      cd ./apps/panel/ && \
      rm -rf lib/spec && \
      echo "🛠️  Building device spec..." && \
      dart tools/build_device_spec.dart && \
      echo "🛠️  Building channel spec..." && \
      dart tools/build_channel_spec.dart && \
      echo "🛠️  Building display config spec..." && \
      dart tools/build_display_grid_spec.dart && \
      echo "🛠️  Building screen breakpoints spec..." && \
      dart tools/build_screen_breakpoints_spec.dart && \
      echo "✅ Spec rebuild complete!"
    description: Cleans the Spec directory, regenerates device and channel specification Dart files.

  build-panel:
    run: |
      echo "🧹 Cleaning previous build artifacts..." && \
      cd ./apps/panel && \
      rm -rf build flutter_assets && \
      dart run flutterpi_tool build \
        --arch=${FB_FLUTTERPI_ARCH:-arm64} \
        ${FB_FLUTTERPI_RELEASE:+--release} \
        --dart-define=APP_VERSION=${FB_FLUTTERPI_APP_VERSION:-1.0.0} \
        --dart-define=APP_BUILD=${FB_FLUTTERPI_APP_BUILD:-1}
    description: Builds the Flutter Pi app for the specified architecture and mode.

  build-panel-arm:
    exec: FB_FLUTTERPI_ARCH=arm melos run build-panel
    description: Builds Flutter Pi app for ARM (32-bit) in debug mode.

  build-panel-arm64:
    exec: FB_FLUTTERPI_ARCH=arm64 melos run build-panel
    description: Builds Flutter Pi app for ARM64 (64-bit) in debug mode.

  build-panel-arm-release:
    exec: FB_FLUTTERPI_ARCH=arm FB_FLUTTERPI_RELEASE=1 melos run build-panel
    description: Builds Flutter Pi app for ARM (32-bit) in release mode.

  build-panel-arm64-release:
    exec: FB_FLUTTERPI_ARCH=arm64 FB_FLUTTERPI_RELEASE=1 melos run build-panel
    description: Builds Flutter Pi app for ARM64 (64-bit) in release mode.

command:
  bootstrap:
    runPubGetInParallel: false
    hooks:
      post: melos rebuild-all
