name: fastybird_smart_app
repository: https://github.com/FastyBird/smart-panel

packages:
  - apps/*

scripts:
  analyze:
    exec: dart analyze .
  generate-run-config:
    run: bash ./bin/generate_app_run_config.sh

command:
  bootstrap:
    runPubGetInParallel: false
