packages:
  - apps/**
  - docs
  # Exclude build folder
  - '!build'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - esbuild
  - sharp
  - sqlite3
  - vue-demi
