packages:
  - apps/**
  - packages/**
  - docs
  # Exclude build folder
  - '!build'
  # Exclude example extension (it's documentation, not part of the build)
  - '!packages/example-extension'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - esbuild
  - sharp
  - sqlite3
  - vue-demi
