import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1749675710804 implements MigrationInterface {
    name = 'Init1749675710804'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_36ec1c9bafc04373563cfb5f83"`);
        await queryRunner.query(`DROP INDEX "IDX_de1447169fa1df5ea8d41bf02a"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices_module_devices" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_conditioner','air_dehumidifier','air_humidifier','air_purifier','alarm','camera','door','doorbell','fan','heater','lighting','lock','media','outlet','pump','robot_vacuum','sensor','speaker','sprinkler','switcher','television','thermostat','valve','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "serviceAddress" varchar, "type" varchar NOT NULL, "haDeviceId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_devices_module_devices"("id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId" FROM "devices_module_devices"`);
        await queryRunner.query(`DROP TABLE "devices_module_devices"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices_module_devices" RENAME TO "devices_module_devices"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36ec1c9bafc04373563cfb5f83" ON "devices_module_devices" ("haDeviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_de1447169fa1df5ea8d41bf02a" ON "devices_module_devices" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_a654e0cabea37168a1a967ab5d"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices_module_channels" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_particulate','alarm','battery','camera','carbon_dioxide','carbon_monoxide','contact','cooler','device_information','door','doorbell','electrical_energy','electrical_power','fan','flow','heater','humidity','illuminance','leak','light','lock','media_input','media_playback','microphone','motion','nitrogen_dioxide','occupancy','outlet','ozone','pressure','robot_vacuum','smoke','speaker','sulphur_dioxide','switcher','television','temperature','thermostat','valve','volatile_organic_compounds','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "deviceId" varchar, "type" varchar NOT NULL, CONSTRAINT "FK_e5e83bd86799131ff462ba199bd" FOREIGN KEY ("deviceId") REFERENCES "devices_module_devices" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_devices_module_channels"("id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type" FROM "devices_module_channels"`);
        await queryRunner.query(`DROP TABLE "devices_module_channels"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices_module_channels" RENAME TO "devices_module_channels"`);
        await queryRunner.query(`CREATE INDEX "IDX_a654e0cabea37168a1a967ab5d" ON "devices_module_channels" ("type") `);
        await queryRunner.query(`CREATE TABLE "temporary_users_module_users" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "isHidden" boolean NOT NULL DEFAULT (0), "password" varchar NOT NULL, "email" varchar, "firstName" varchar, "lastName" varchar, "username" varchar NOT NULL, "role" varchar CHECK( "role" IN ('owner','admin','user','display') ) NOT NULL DEFAULT ('user'), CONSTRAINT "UQ_2a324415aadd7601a86ea76143a" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_users_module_users"("id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role") SELECT "id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role" FROM "users_module_users"`);
        await queryRunner.query(`DROP TABLE "users_module_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users_module_users" RENAME TO "users_module_users"`);
        await queryRunner.query(`DROP INDEX "IDX_36ec1c9bafc04373563cfb5f83"`);
        await queryRunner.query(`DROP INDEX "IDX_de1447169fa1df5ea8d41bf02a"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices_module_devices" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_conditioner','air_dehumidifier','air_humidifier','air_purifier','alarm','camera','door','doorbell','fan','heater','lighting','lock','media','outlet','pump','robot_vacuum','sensor','speaker','sprinkler','switcher','television','thermostat','valve','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "serviceAddress" varchar, "type" varchar NOT NULL, "haDeviceId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_devices_module_devices"("id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId" FROM "devices_module_devices"`);
        await queryRunner.query(`DROP TABLE "devices_module_devices"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices_module_devices" RENAME TO "devices_module_devices"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36ec1c9bafc04373563cfb5f83" ON "devices_module_devices" ("haDeviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_de1447169fa1df5ea8d41bf02a" ON "devices_module_devices" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_a654e0cabea37168a1a967ab5d"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices_module_channels" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_particulate','alarm','battery','camera','carbon_dioxide','carbon_monoxide','contact','cooler','device_information','door','doorbell','electrical_energy','electrical_power','fan','flow','heater','humidity','illuminance','leak','light','lock','media_input','media_playback','microphone','motion','nitrogen_dioxide','occupancy','outlet','ozone','pressure','robot_vacuum','smoke','speaker','sulphur_dioxide','switcher','television','temperature','thermostat','valve','volatile_organic_compounds','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "deviceId" varchar, "type" varchar NOT NULL, CONSTRAINT "FK_e5e83bd86799131ff462ba199bd" FOREIGN KEY ("deviceId") REFERENCES "devices_module_devices" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_devices_module_channels"("id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type" FROM "devices_module_channels"`);
        await queryRunner.query(`DROP TABLE "devices_module_channels"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices_module_channels" RENAME TO "devices_module_channels"`);
        await queryRunner.query(`CREATE INDEX "IDX_a654e0cabea37168a1a967ab5d" ON "devices_module_channels" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_98ffd1e6ff9c4463c3e7d9a9c7"`);
        await queryRunner.query(`CREATE TABLE "temporary_devices_module_channels_properties" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','active','angle','brightness','color_blue','color_green','color_red','color_temperature','color_white','connection_type','consumption','current','density','detected','direction','distance','duration','event','fault','firmware_revision','frequency','hardware_revision','hue','humidity','in_use','infrared','input_source','level','link_quality','locked','manufacturer','measured','model','mode','obstruction','on','over_current','over_voltage','over_power','pan','peak_level','percentage','position','power','rate','remaining','remote_key','saturation','serial_number','source','speed','status','swing','tampered','temperature','tilt','track','type','units','voltage','volume','zoom') ) NOT NULL DEFAULT ('generic'), "name" varchar, "permissions" text NOT NULL DEFAULT ('ro'), "dataType" varchar CHECK( "dataType" IN ('char','uchar','short','ushort','int','uint','float','bool','string','enum','unknown') ) NOT NULL DEFAULT ('unknown'), "unit" varchar, "format" json, "invalid" text, "step" real, "channelId" varchar, "type" varchar NOT NULL, "haAttribute" varchar, "haEntityId" varchar, CONSTRAINT "FK_25ddb149b40ce110e482ccd2a3d" FOREIGN KEY ("channelId") REFERENCES "devices_module_channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_devices_module_channels_properties"("id", "createdAt", "updatedAt", "category", "name", "permissions", "dataType", "unit", "format", "invalid", "step", "channelId", "type", "haAttribute", "haEntityId") SELECT "id", "createdAt", "updatedAt", "category", "name", "permissions", "dataType", "unit", "format", "invalid", "step", "channelId", "type", "haAttribute", "haEntityId" FROM "devices_module_channels_properties"`);
        await queryRunner.query(`DROP TABLE "devices_module_channels_properties"`);
        await queryRunner.query(`ALTER TABLE "temporary_devices_module_channels_properties" RENAME TO "devices_module_channels_properties"`);
        await queryRunner.query(`CREATE INDEX "IDX_98ffd1e6ff9c4463c3e7d9a9c7" ON "devices_module_channels_properties" ("type") `);
        await queryRunner.query(`CREATE TABLE "temporary_users_module_users" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "isHidden" boolean NOT NULL DEFAULT (0), "password" varchar NOT NULL, "email" varchar, "firstName" varchar, "lastName" varchar, "username" varchar NOT NULL, "role" varchar CHECK( "role" IN ('owner','admin','user','display') ) NOT NULL DEFAULT ('user'), CONSTRAINT "UQ_2a324415aadd7601a86ea76143a" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_users_module_users"("id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role") SELECT "id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role" FROM "users_module_users"`);
        await queryRunner.query(`DROP TABLE "users_module_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users_module_users" RENAME TO "users_module_users"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_module_users" RENAME TO "temporary_users_module_users"`);
        await queryRunner.query(`CREATE TABLE "users_module_users" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "isHidden" boolean NOT NULL DEFAULT (0), "password" varchar NOT NULL, "email" varchar, "firstName" varchar, "lastName" varchar, "username" varchar NOT NULL, "role" varchar CHECK( "role" IN ('owner','admin','user','display') ) NOT NULL DEFAULT ('user'), CONSTRAINT "UQ_2a324415aadd7601a86ea76143a" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users_module_users"("id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role") SELECT "id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role" FROM "temporary_users_module_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users_module_users"`);
        await queryRunner.query(`DROP INDEX "IDX_98ffd1e6ff9c4463c3e7d9a9c7"`);
        await queryRunner.query(`ALTER TABLE "devices_module_channels_properties" RENAME TO "temporary_devices_module_channels_properties"`);
        await queryRunner.query(`CREATE TABLE "devices_module_channels_properties" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','active','angle','brightness','color_blue','color_green','color_red','color_temperature','color_white','connection_type','consumption','current','density','detected','direction','distance','duration','event','fault','firmware_revision','frequency','hardware_revision','hue','humidity','in_use','infrared','input_source','level','link_quality','locked','manufacturer','measured','model','mode','obstruction','on','over_current','over_voltage','over_power','pan','peak_level','percentage','position','power','rate','remaining','remote_key','saturation','serial_number','source','speed','status','swing','tampered','temperature','tilt','track','type','units','voltage','volume','zoom') ) NOT NULL DEFAULT ('generic'), "name" varchar, "permissions" text NOT NULL DEFAULT ('ro'), "dataType" varchar CHECK( "dataType" IN ('char','uchar','short','ushort','int','uint','float','bool','string','enum','unknown') ) NOT NULL DEFAULT ('unknown'), "unit" varchar, "format" json, "invalid" text, "step" real, "channelId" varchar, "type" varchar NOT NULL, "haAttribute" varchar, "haEntityId" varchar, CONSTRAINT "FK_25ddb149b40ce110e482ccd2a3d" FOREIGN KEY ("channelId") REFERENCES "devices_module_channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "devices_module_channels_properties"("id", "createdAt", "updatedAt", "category", "name", "permissions", "dataType", "unit", "format", "invalid", "step", "channelId", "type", "haAttribute", "haEntityId") SELECT "id", "createdAt", "updatedAt", "category", "name", "permissions", "dataType", "unit", "format", "invalid", "step", "channelId", "type", "haAttribute", "haEntityId" FROM "temporary_devices_module_channels_properties"`);
        await queryRunner.query(`DROP TABLE "temporary_devices_module_channels_properties"`);
        await queryRunner.query(`CREATE INDEX "IDX_98ffd1e6ff9c4463c3e7d9a9c7" ON "devices_module_channels_properties" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_a654e0cabea37168a1a967ab5d"`);
        await queryRunner.query(`ALTER TABLE "devices_module_channels" RENAME TO "temporary_devices_module_channels"`);
        await queryRunner.query(`CREATE TABLE "devices_module_channels" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_particulate','alarm','battery','camera','carbon_dioxide','carbon_monoxide','contact','cooler','device_information','door','doorbell','electrical_energy','electrical_power','fan','flow','heater','humidity','illuminance','leak','light','lock','media_input','media_playback','microphone','motion','nitrogen_dioxide','occupancy','outlet','ozone','pressure','robot_vacuum','smoke','speaker','sulphur_dioxide','switcher','television','temperature','thermostat','valve','volatile_organic_compounds','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "deviceId" varchar, "type" varchar NOT NULL, CONSTRAINT "FK_e5e83bd86799131ff462ba199bd" FOREIGN KEY ("deviceId") REFERENCES "devices_module_devices" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "devices_module_channels"("id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type" FROM "temporary_devices_module_channels"`);
        await queryRunner.query(`DROP TABLE "temporary_devices_module_channels"`);
        await queryRunner.query(`CREATE INDEX "IDX_a654e0cabea37168a1a967ab5d" ON "devices_module_channels" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_de1447169fa1df5ea8d41bf02a"`);
        await queryRunner.query(`DROP INDEX "IDX_36ec1c9bafc04373563cfb5f83"`);
        await queryRunner.query(`ALTER TABLE "devices_module_devices" RENAME TO "temporary_devices_module_devices"`);
        await queryRunner.query(`CREATE TABLE "devices_module_devices" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_conditioner','air_dehumidifier','air_humidifier','air_purifier','alarm','camera','door','doorbell','fan','heater','lighting','lock','media','outlet','pump','robot_vacuum','sensor','speaker','sprinkler','switcher','television','thermostat','valve','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "serviceAddress" varchar, "type" varchar NOT NULL, "haDeviceId" varchar)`);
        await queryRunner.query(`INSERT INTO "devices_module_devices"("id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId" FROM "temporary_devices_module_devices"`);
        await queryRunner.query(`DROP TABLE "temporary_devices_module_devices"`);
        await queryRunner.query(`CREATE INDEX "IDX_de1447169fa1df5ea8d41bf02a" ON "devices_module_devices" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36ec1c9bafc04373563cfb5f83" ON "devices_module_devices" ("haDeviceId") `);
        await queryRunner.query(`ALTER TABLE "users_module_users" RENAME TO "temporary_users_module_users"`);
        await queryRunner.query(`CREATE TABLE "users_module_users" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "isHidden" boolean NOT NULL DEFAULT (0), "password" varchar NOT NULL, "email" varchar, "firstName" varchar, "lastName" varchar, "username" varchar NOT NULL, "role" varchar CHECK( "role" IN ('owner','admin','user','display') ) NOT NULL DEFAULT ('user'), CONSTRAINT "UQ_2a324415aadd7601a86ea76143a" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users_module_users"("id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role") SELECT "id", "createdAt", "updatedAt", "isHidden", "password", "email", "firstName", "lastName", "username", "role" FROM "temporary_users_module_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users_module_users"`);
        await queryRunner.query(`DROP INDEX "IDX_a654e0cabea37168a1a967ab5d"`);
        await queryRunner.query(`ALTER TABLE "devices_module_channels" RENAME TO "temporary_devices_module_channels"`);
        await queryRunner.query(`CREATE TABLE "devices_module_channels" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_particulate','alarm','battery','camera','carbon_dioxide','carbon_monoxide','contact','cooler','device_information','door','doorbell','electrical_energy','electrical_power','fan','flow','heater','humidity','illuminance','leak','light','lock','media_input','media_playback','microphone','motion','nitrogen_dioxide','occupancy','outlet','ozone','pressure','robot_vacuum','smoke','speaker','sulphur_dioxide','switcher','television','temperature','thermostat','valve','volatile_organic_compounds','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "deviceId" varchar, "type" varchar NOT NULL, CONSTRAINT "FK_e5e83bd86799131ff462ba199bd" FOREIGN KEY ("deviceId") REFERENCES "devices_module_devices" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "devices_module_channels"("id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "deviceId", "type" FROM "temporary_devices_module_channels"`);
        await queryRunner.query(`DROP TABLE "temporary_devices_module_channels"`);
        await queryRunner.query(`CREATE INDEX "IDX_a654e0cabea37168a1a967ab5d" ON "devices_module_channels" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_de1447169fa1df5ea8d41bf02a"`);
        await queryRunner.query(`DROP INDEX "IDX_36ec1c9bafc04373563cfb5f83"`);
        await queryRunner.query(`ALTER TABLE "devices_module_devices" RENAME TO "temporary_devices_module_devices"`);
        await queryRunner.query(`CREATE TABLE "devices_module_devices" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updatedAt" datetime, "category" varchar CHECK( "category" IN ('generic','air_conditioner','air_dehumidifier','air_humidifier','air_purifier','alarm','camera','door','doorbell','fan','heater','lighting','lock','media','outlet','pump','robot_vacuum','sensor','speaker','sprinkler','switcher','television','thermostat','valve','window_covering') ) NOT NULL DEFAULT ('generic'), "name" varchar NOT NULL, "description" varchar, "serviceAddress" varchar, "type" varchar NOT NULL, "haDeviceId" varchar)`);
        await queryRunner.query(`INSERT INTO "devices_module_devices"("id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId") SELECT "id", "createdAt", "updatedAt", "category", "name", "description", "serviceAddress", "type", "haDeviceId" FROM "temporary_devices_module_devices"`);
        await queryRunner.query(`DROP TABLE "temporary_devices_module_devices"`);
        await queryRunner.query(`CREATE INDEX "IDX_de1447169fa1df5ea8d41bf02a" ON "devices_module_devices" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36ec1c9bafc04373563cfb5f83" ON "devices_module_devices" ("haDeviceId") `);
    }

}
