import { beforeEach, describe, expect, it, vi } from 'vitest';

import { DevicesModuleDeviceCategory, SimulatorPluginBehaviorMode } from '../../../openapi.constants';

import type { ISimulatorGenerationOptions } from './useSimulatorGenerationWizard';
import { useSimulatorGenerationWizard } from './useSimulatorGenerationWizard';

const backendClient = {
	GET: vi.fn(),
	POST: vi.fn(),
};

const devicesStore = {
	fetch: vi.fn(),
};

const logger = {
	debug: vi.fn(),
	info: vi.fn(),
	warn: vi.fn(),
	error: vi.fn(),
};

vi.mock('../../../common', async () => {
	const actual = await vi.importActual('../../../common');

	return {
		...actual,
		injectStoresManager: () => ({ getStore: vi.fn(() => devicesStore) }),
		useBackend: () => ({ client: backendClient }),
		useLogger: () => logger,
	};
});

const options = (overrides: Partial<ISimulatorGenerationOptions> = {}): ISimulatorGenerationOptions => ({
	category: DevicesModuleDeviceCategory.lighting,
	count: 1,
	namePrefix: 'Test light',
	description: 'Generated by the wizard',
	roomId: '11111111-1111-4111-8111-111111111111',
	requiredChannelsOnly: true,
	requiredPropertiesOnly: false,
	autoSimulate: true,
	simulateInterval: 5_000,
	behaviorMode: SimulatorPluginBehaviorMode.realistic,
	...overrides,
});

const success = (id: string) => ({
	data: { data: { id } },
	response: { status: 201 },
});

describe('useSimulatorGenerationWizard', () => {
	beforeEach(() => {
		vi.clearAllMocks();
		devicesStore.fetch.mockResolvedValue([]);
	});

	it('fetches and caches the available categories when requested', async () => {
		backendClient.GET.mockResolvedValue({
			data: {
				data: [{ category: 'lighting', name: 'Lighting', description: 'Lights and strips' }],
			},
			response: { status: 200 },
		});
		const wizard = useSimulatorGenerationWizard();

		await Promise.all([wizard.fetchCategories(), wizard.fetchCategories()]);
		await wizard.fetchCategories();

		expect(backendClient.GET).toHaveBeenCalledTimes(1);
		expect(backendClient.GET).toHaveBeenCalledWith('/plugins/simulator/simulator/categories', {});
		expect(wizard.categories.value).toEqual([{ category: 'lighting', name: 'Lighting', description: 'Lights and strips' }]);
		expect(wizard.loadingCategories.value).toBe(false);
		expect(wizard.categoriesError.value).toBeNull();
	});

	it('exposes a category loading error and allows a later retry', async () => {
		backendClient.GET.mockResolvedValueOnce({
			data: undefined,
			error: { error: { details: [{ reason: 'Simulator is unavailable' }] } },
			response: { status: 503 },
		}).mockResolvedValueOnce({ data: { data: [] }, response: { status: 200 } });
		const wizard = useSimulatorGenerationWizard();

		await expect(wizard.fetchCategories()).rejects.toThrow('Simulator is unavailable');
		expect(wizard.categoriesError.value).toBe('Simulator is unavailable');

		await wizard.fetchCategories();

		expect(backendClient.GET).toHaveBeenCalledTimes(2);
		expect(wizard.categoriesError.value).toBeNull();
	});

	it('uses the prefix unchanged for one device and sends every generation option', async () => {
		backendClient.POST.mockResolvedValue(success('device-1'));
		const wizard = useSimulatorGenerationWizard();

		await wizard.generate(options());

		expect(backendClient.POST).toHaveBeenCalledWith('/plugins/simulator/simulator/generate', {
			body: {
				data: {
					category: 'lighting',
					name: 'Test light',
					description: 'Generated by the wizard',
					room_id: '11111111-1111-4111-8111-111111111111',
					required_channels_only: true,
					required_properties_only: false,
					auto_simulate: true,
					simulate_interval: 5_000,
					behavior_mode: 'realistic',
				},
			},
		});
		expect(wizard.results.value).toEqual([{ name: 'Test light', success: true, deviceId: 'device-1' }]);
		expect(devicesStore.fetch).toHaveBeenCalledTimes(1);
	});

	it('ignores an inactive interval when automatic simulation is disabled', async () => {
		backendClient.POST.mockResolvedValue(success('device-1'));
		const wizard = useSimulatorGenerationWizard();

		await wizard.generate(options({ autoSimulate: false, simulateInterval: 0 }));

		expect(backendClient.POST).toHaveBeenCalledWith(
			'/plugins/simulator/simulator/generate',
			expect.objectContaining({
				body: {
					data: expect.not.objectContaining({ simulate_interval: expect.anything() }),
				},
			})
		);
		expect(backendClient.POST.mock.calls[0]?.[1].body.data.auto_simulate).toBe(false);
		expect(wizard.results.value).toEqual([{ name: 'Test light', success: true, deviceId: 'device-1' }]);
		expect(wizard.generationError.value).toBeNull();
	});

	it('limits generation concurrency to three and retains ordered partial results', async () => {
		let active = 0;
		let maximumActive = 0;
		const releases: (() => void)[] = [];

		backendClient.POST.mockImplementation(
			(_path: string, request: { body: { data: { name: string } } }) =>
				new Promise((resolve) => {
					active += 1;
					maximumActive = Math.max(maximumActive, active);
					releases.push(() => {
						active -= 1;
						const name = request.body.data.name;
						resolve(
							name === 'Sensor 3'
								? {
										data: undefined,
										error: { error: { details: [{ reason: 'Creation rejected' }] } },
										response: { status: 422 },
									}
								: success(`id-${name.split(' ')[1]}`)
						);
					});
				})
		);
		const wizard = useSimulatorGenerationWizard();

		const generation = wizard.generate(options({ count: 5, namePrefix: 'Sensor' }));
		await vi.waitFor(() => expect(releases).toHaveLength(3));
		expect(maximumActive).toBe(3);

		releases.shift()?.();
		await vi.waitFor(() => expect(releases).toHaveLength(3));
		releases.shift()?.();
		await vi.waitFor(() => expect(releases).toHaveLength(3));
		while (releases.length > 0) releases.shift()?.();

		await generation;

		expect(maximumActive).toBe(3);
		expect(wizard.results.value).toEqual([
			{ name: 'Sensor 1', success: true, deviceId: 'id-1' },
			{ name: 'Sensor 2', success: true, deviceId: 'id-2' },
			{ name: 'Sensor 3', success: false, error: 'Creation rejected' },
			{ name: 'Sensor 4', success: true, deviceId: 'id-4' },
			{ name: 'Sensor 5', success: true, deviceId: 'id-5' },
		]);
		expect(devicesStore.fetch).toHaveBeenCalledTimes(1);
	});

	it('does not refresh the device store when every item fails', async () => {
		backendClient.POST.mockRejectedValue(new Error('Network unavailable'));
		const wizard = useSimulatorGenerationWizard();

		await wizard.generate(options({ count: 2 }));

		expect(wizard.results.value).toEqual([
			{ name: 'Test light 1', success: false, error: 'Network unavailable' },
			{ name: 'Test light 2', success: false, error: 'Network unavailable' },
		]);
		expect(devicesStore.fetch).not.toHaveBeenCalled();
		expect(wizard.generating.value).toBe(false);
	});

	it('enforces the 1-20 batch limit before sending requests', async () => {
		const wizard = useSimulatorGenerationWizard();

		await expect(wizard.generate(options({ count: 21 }))).rejects.toThrow('between 1 and 20');

		expect(backendClient.POST).not.toHaveBeenCalled();
		expect(wizard.generationError.value).toBe('Device count must be an integer between 1 and 20');
	});

	it('resets generation results and errors without discarding cached categories', async () => {
		backendClient.GET.mockResolvedValue({ data: { data: [] }, response: { status: 200 } });
		backendClient.POST.mockRejectedValue(new Error('Generation failed'));
		const wizard = useSimulatorGenerationWizard();
		await wizard.fetchCategories();
		await wizard.generate(options());

		wizard.reset();

		expect(wizard.results.value).toEqual([]);
		expect(wizard.generationError.value).toBeNull();
		expect(wizard.categories.value).toEqual([]);
		await wizard.fetchCategories();
		expect(backendClient.GET).toHaveBeenCalledTimes(1);
	});
});
