# .github/actions/publish-npm-package/action.yml

name: "Publish NPM Package"

description: "Publishes an NPM package with optional version bump and tagging"

inputs:
  package-path:
    description: "Path to the package"
    required: true
  tag:
    description: "NPM tag (e.g. latest, alpha)"
    required: false
  npm-version-command:
    description: "Version bump (e.g. patch, minor)"
    required: false
  pre-id:
    description: "Pre-release ID (e.g. alpha, beta)"
    required: false
    default: ""
  dynamically-adjust-version:
    description: "Run custom version script"
    required: false
    default: "false"
  npm-auth-token:
    description: "NPM Auth Token"
    required: true
  npm-registry-url:
    description: "NPM registry"
    default: "https://registry.npmjs.org"
    required: false
  npm-registry:
    description: "NPM registry (used in .npmrc auth entry)"
    default: "registry.npmjs.org"
    required: false

outputs:
  NPM_VERSION:
    description: "Published NPM version"

runs:
  using: "composite"
  steps:
    - name: "Configure .npmrc for GitHub NPM"
      working-directory: ${{ inputs.package-path }}
      shell: bash
      run: |
        echo "@fastybird:registry=${{ inputs.npm-registry-url }}" >> .npmrc
        echo "//${{ inputs.npm-registry }}/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

    - name: "Adjust version dynamically"
      if: ${{ inputs.dynamically-adjust-version == 'true' }}
      working-directory: ${{ inputs.package-path }}
      run: "node ../scripts/npm-version-script.js ${{ github.ref }} ${{ inputs.tag }}"
      shell: bash

    - name: "Run npm version (with git commit)"
      if: ${{ inputs.npm-version-command != '' && inputs.dynamically-adjust-version == 'false' }}
      working-directory: ${{ inputs.package-path }}
      run: "pnpm version ${{ inputs.npm-version-command }} --preid=${{ inputs.pre-id }} --allow-same-version"
      shell: bash

    - name: "Run npm version (no git commit)"
      if: ${{ inputs.npm-version-command != '' && inputs.dynamically-adjust-version == 'true' }}
      working-directory: ${{ inputs.package-path }}
      run: "pnpm version ${{ inputs.npm-version-command }} --preid=${{ inputs.pre-id }} --no-git-tag-version --allow-same-version"
      shell: bash

    - name: "Publish to NPM"
      working-directory: ${{ inputs.package-path }}
      run: |
        VERSION=$(jq -r .version package.json)
        PACKAGE_NAME=$(jq -r .name package.json)
        
        if npm view $PACKAGE_NAME@$VERSION --registry=${{ inputs.npm-registry-url }} > /dev/null 2>&1; then
          echo "ðŸ” Skipping: $PACKAGE_NAME@$VERSION already exists on registry"
        else
          if [ -z "${{ inputs.tag }}" ]; then
            pnpm publish --registry=${{ inputs.npm-registry-url }} --access public --provenance --no-git-checks
          else
            pnpm publish --registry=${{ inputs.npm-registry-url }} --access public --tag=${{ inputs.tag }} --provenance --no-git-checks
          fi
        fi
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

    - name: "Extract and output version"
      id: "get-version"
      working-directory: ${{ inputs.package-path }}
      run: echo "NPM_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Export version from composite to workflow"
      run: echo "NPM_VERSION=${{ steps.get-version.outputs.NPM_VERSION }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Notice"
      run: echo "::notice::Published ${{ inputs.package-path }} on NPM as ${{ steps.get-version.outputs.NPM_VERSION }}"
      shell: bash
