import { DevicesChannelCategory, DevicesChannelPropertyCategory, DevicesDeviceCategory } from '../../openapi';

export const deviceChannelsSpecificationOrder: Record<DevicesDeviceCategory, DevicesChannelCategory[]> = {
	[DevicesDeviceCategory.generic]: [],
	[DevicesDeviceCategory.air_conditioner]: [
		DevicesChannelCategory.cooler,
		DevicesChannelCategory.heater,
		DevicesChannelCategory.fan,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.air_dehumidifier]: [
		DevicesChannelCategory.cooler,
		DevicesChannelCategory.fan,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.air_humidifier]: [
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.switcher,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.fan,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.air_purifier]: [
		DevicesChannelCategory.fan,
		DevicesChannelCategory.air_particulate,
		DevicesChannelCategory.carbon_dioxide,
		DevicesChannelCategory.carbon_monoxide,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.nitrogen_dioxide,
		DevicesChannelCategory.ozone,
		DevicesChannelCategory.pressure,
		DevicesChannelCategory.sulphur_dioxide,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.volatile_organic_compounds,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.alarm]: [DevicesChannelCategory.alarm, DevicesChannelCategory.device_information],
	[DevicesDeviceCategory.camera]: [
		DevicesChannelCategory.camera,
		DevicesChannelCategory.motion,
		DevicesChannelCategory.microphone,
		DevicesChannelCategory.speaker,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.light,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.door]: [
		DevicesChannelCategory.door,
		DevicesChannelCategory.lock,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.motion,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.doorbell]: [
		DevicesChannelCategory.doorbell,
		DevicesChannelCategory.camera,
		DevicesChannelCategory.lock,
		DevicesChannelCategory.motion,
		DevicesChannelCategory.microphone,
		DevicesChannelCategory.speaker,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.light,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.fan]: [
		DevicesChannelCategory.fan,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.heater]: [
		DevicesChannelCategory.heater,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.lighting]: [
		DevicesChannelCategory.light,
		DevicesChannelCategory.illuminance,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.lock]: [
		DevicesChannelCategory.lock,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.motion,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.media]: [
		DevicesChannelCategory.media_input,
		DevicesChannelCategory.media_playback,
		DevicesChannelCategory.microphone,
		DevicesChannelCategory.speaker,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.outlet]: [
		DevicesChannelCategory.outlet,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.pump]: [
		DevicesChannelCategory.flow,
		DevicesChannelCategory.switcher,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.pressure,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.robot_vacuum]: [
		DevicesChannelCategory.robot_vacuum,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.sensor]: [
		DevicesChannelCategory.air_particulate,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.carbon_dioxide,
		DevicesChannelCategory.carbon_monoxide,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.illuminance,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.motion,
		DevicesChannelCategory.nitrogen_dioxide,
		DevicesChannelCategory.occupancy,
		DevicesChannelCategory.ozone,
		DevicesChannelCategory.pressure,
		DevicesChannelCategory.smoke,
		DevicesChannelCategory.sulphur_dioxide,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.volatile_organic_compounds,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.speaker]: [
		DevicesChannelCategory.speaker,
		DevicesChannelCategory.media_input,
		DevicesChannelCategory.media_playback,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.sprinkler]: [
		DevicesChannelCategory.valve,
		DevicesChannelCategory.flow,
		DevicesChannelCategory.pressure,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.switcher]: [
		DevicesChannelCategory.switcher,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.television]: [DevicesChannelCategory.television, DevicesChannelCategory.speaker, DevicesChannelCategory.device_information],
	[DevicesDeviceCategory.thermostat]: [
		DevicesChannelCategory.thermostat,
		DevicesChannelCategory.cooler,
		DevicesChannelCategory.heater,
		DevicesChannelCategory.temperature,
		DevicesChannelCategory.humidity,
		DevicesChannelCategory.contact,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.valve]: [
		DevicesChannelCategory.valve,
		DevicesChannelCategory.pressure,
		DevicesChannelCategory.flow,
		DevicesChannelCategory.leak,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
	[DevicesDeviceCategory.window_covering]: [
		DevicesChannelCategory.window_covering,
		DevicesChannelCategory.battery,
		DevicesChannelCategory.electrical_energy,
		DevicesChannelCategory.electrical_power,
		DevicesChannelCategory.device_information,
	],
};

export const deviceChannelsSpecificationMappers: Record<
	DevicesDeviceCategory,
	{
		required: DevicesChannelCategory[];
		optional: DevicesChannelCategory[];
		multiple?: DevicesChannelCategory[];
	}
> = {
	[DevicesDeviceCategory.generic]: {
		required: [],
		optional: [],
	},
	[DevicesDeviceCategory.air_conditioner]: {
		required: [
			DevicesChannelCategory.cooler,
			DevicesChannelCategory.device_information,
			DevicesChannelCategory.fan,
			DevicesChannelCategory.temperature,
		],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.heater,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.leak,
		],
	},
	[DevicesDeviceCategory.air_dehumidifier]: {
		required: [DevicesChannelCategory.cooler, DevicesChannelCategory.device_information, DevicesChannelCategory.humidity],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.fan,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.temperature,
		],
	},
	[DevicesDeviceCategory.air_humidifier]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.humidity, DevicesChannelCategory.switcher],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.fan,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.temperature,
		],
	},
	[DevicesDeviceCategory.air_purifier]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.fan],
		optional: [
			DevicesChannelCategory.air_particulate,
			DevicesChannelCategory.carbon_dioxide,
			DevicesChannelCategory.carbon_monoxide,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.nitrogen_dioxide,
			DevicesChannelCategory.ozone,
			DevicesChannelCategory.pressure,
			DevicesChannelCategory.sulphur_dioxide,
			DevicesChannelCategory.temperature,
			DevicesChannelCategory.volatile_organic_compounds,
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
		],
	},
	[DevicesDeviceCategory.alarm]: {
		required: [DevicesChannelCategory.alarm, DevicesChannelCategory.device_information],
		optional: [],
	},
	[DevicesDeviceCategory.camera]: {
		required: [DevicesChannelCategory.camera, DevicesChannelCategory.device_information],
		optional: [
			DevicesChannelCategory.battery,
			DevicesChannelCategory.contact,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.light,
			DevicesChannelCategory.microphone,
			DevicesChannelCategory.motion,
			DevicesChannelCategory.speaker,
			DevicesChannelCategory.temperature,
		],
	},
	[DevicesDeviceCategory.door]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.door],
		optional: [DevicesChannelCategory.battery, DevicesChannelCategory.contact, DevicesChannelCategory.lock, DevicesChannelCategory.motion],
	},
	[DevicesDeviceCategory.doorbell]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.doorbell],
		optional: [
			DevicesChannelCategory.battery,
			DevicesChannelCategory.camera,
			DevicesChannelCategory.contact,
			DevicesChannelCategory.light,
			DevicesChannelCategory.lock,
			DevicesChannelCategory.microphone,
			DevicesChannelCategory.motion,
			DevicesChannelCategory.speaker,
		],
	},
	[DevicesDeviceCategory.fan]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.fan],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power],
	},
	[DevicesDeviceCategory.heater]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.heater, DevicesChannelCategory.temperature],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power, DevicesChannelCategory.humidity],
	},
	[DevicesDeviceCategory.lighting]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.light],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power, DevicesChannelCategory.illuminance],
		multiple: [DevicesChannelCategory.light],
	},
	[DevicesDeviceCategory.lock]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.lock],
		optional: [DevicesChannelCategory.battery, DevicesChannelCategory.contact, DevicesChannelCategory.motion],
	},
	[DevicesDeviceCategory.media]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.media_input, DevicesChannelCategory.media_playback],
		optional: [DevicesChannelCategory.microphone, DevicesChannelCategory.speaker],
	},
	[DevicesDeviceCategory.outlet]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.outlet],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power],
		multiple: [DevicesChannelCategory.outlet],
	},
	[DevicesDeviceCategory.pump]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.flow, DevicesChannelCategory.switcher],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.pressure,
		],
	},
	[DevicesDeviceCategory.robot_vacuum]: {
		required: [DevicesChannelCategory.battery, DevicesChannelCategory.device_information, DevicesChannelCategory.robot_vacuum],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power, DevicesChannelCategory.leak],
	},
	[DevicesDeviceCategory.sensor]: {
		required: [DevicesChannelCategory.device_information],
		optional: [
			DevicesChannelCategory.air_particulate,
			DevicesChannelCategory.battery,
			DevicesChannelCategory.carbon_dioxide,
			DevicesChannelCategory.carbon_monoxide,
			DevicesChannelCategory.contact,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.illuminance,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.motion,
			DevicesChannelCategory.nitrogen_dioxide,
			DevicesChannelCategory.occupancy,
			DevicesChannelCategory.ozone,
			DevicesChannelCategory.pressure,
			DevicesChannelCategory.smoke,
			DevicesChannelCategory.sulphur_dioxide,
			DevicesChannelCategory.temperature,
			DevicesChannelCategory.volatile_organic_compounds,
		],
	},
	[DevicesDeviceCategory.speaker]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.speaker],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.media_input,
			DevicesChannelCategory.media_playback,
		],
	},
	[DevicesDeviceCategory.sprinkler]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.valve],
		optional: [
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.flow,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.pressure,
		],
		multiple: [DevicesChannelCategory.valve],
	},
	[DevicesDeviceCategory.switcher]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.switcher],
		optional: [DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power],
		multiple: [DevicesChannelCategory.switcher],
	},
	[DevicesDeviceCategory.television]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.speaker, DevicesChannelCategory.television],
		optional: [],
	},
	[DevicesDeviceCategory.thermostat]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.temperature, DevicesChannelCategory.thermostat],
		optional: [
			DevicesChannelCategory.contact,
			DevicesChannelCategory.cooler,
			DevicesChannelCategory.heater,
			DevicesChannelCategory.humidity,
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
		],
	},
	[DevicesDeviceCategory.valve]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.valve],
		optional: [
			DevicesChannelCategory.battery,
			DevicesChannelCategory.electrical_energy,
			DevicesChannelCategory.electrical_power,
			DevicesChannelCategory.flow,
			DevicesChannelCategory.leak,
			DevicesChannelCategory.pressure,
		],
	},
	[DevicesDeviceCategory.window_covering]: {
		required: [DevicesChannelCategory.device_information, DevicesChannelCategory.window_covering],
		optional: [DevicesChannelCategory.battery, DevicesChannelCategory.electrical_energy, DevicesChannelCategory.electrical_power],
	},
};

export const channelChannelsPropertiesSpecificationMappers: Record<
	DevicesChannelCategory,
	{
		required: DevicesChannelPropertyCategory[];
		optional: DevicesChannelPropertyCategory[];
	}
> = {
	[DevicesChannelCategory.generic]: {
		required: [],
		optional: [],
	},
	[DevicesChannelCategory.air_particulate]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.mode,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.alarm]: {
		required: [],
		optional: [],
	},
	[DevicesChannelCategory.battery]: {
		required: [DevicesChannelPropertyCategory.percentage, DevicesChannelPropertyCategory.status],
		optional: [DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.camera]: {
		required: [DevicesChannelPropertyCategory.status, DevicesChannelPropertyCategory.source],
		optional: [
			DevicesChannelPropertyCategory.zoom,
			DevicesChannelPropertyCategory.pan,
			DevicesChannelPropertyCategory.tilt,
			DevicesChannelPropertyCategory.infrared,
			DevicesChannelPropertyCategory.fault,
		],
	},
	[DevicesChannelCategory.carbon_dioxide]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.peak_level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.carbon_monoxide]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.peak_level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.contact]: {
		required: [DevicesChannelPropertyCategory.detected],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault, DevicesChannelPropertyCategory.tampered],
	},
	[DevicesChannelCategory.cooler]: {
		required: [DevicesChannelPropertyCategory.temperature, DevicesChannelPropertyCategory.status],
		optional: [],
	},
	[DevicesChannelCategory.device_information]: {
		required: [
			DevicesChannelPropertyCategory.manufacturer,
			DevicesChannelPropertyCategory.model,
			DevicesChannelPropertyCategory.serial_number,
			DevicesChannelPropertyCategory.firmware_revision,
		],
		optional: [
			DevicesChannelPropertyCategory.hardware_revision,
			DevicesChannelPropertyCategory.link_quality,
			DevicesChannelPropertyCategory.connection_type,
			DevicesChannelPropertyCategory.fault,
		],
	},
	[DevicesChannelCategory.door]: {
		required: [
			DevicesChannelPropertyCategory.obstruction,
			DevicesChannelPropertyCategory.status,
			DevicesChannelPropertyCategory.position,
			DevicesChannelPropertyCategory.type,
		],
		optional: [DevicesChannelPropertyCategory.percentage, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.doorbell]: {
		required: [DevicesChannelPropertyCategory.event],
		optional: [DevicesChannelPropertyCategory.brightness, DevicesChannelPropertyCategory.tampered],
	},
	[DevicesChannelCategory.electrical_energy]: {
		required: [DevicesChannelPropertyCategory.consumption, DevicesChannelPropertyCategory.rate],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.electrical_power]: {
		required: [
			DevicesChannelPropertyCategory.power,
			DevicesChannelPropertyCategory.voltage,
			DevicesChannelPropertyCategory.current,
			DevicesChannelPropertyCategory.frequency,
		],
		optional: [
			DevicesChannelPropertyCategory.over_voltage,
			DevicesChannelPropertyCategory.over_current,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
		],
	},
	[DevicesChannelCategory.fan]: {
		required: [DevicesChannelPropertyCategory.on],
		optional: [DevicesChannelPropertyCategory.swing, DevicesChannelPropertyCategory.speed, DevicesChannelPropertyCategory.direction],
	},
	[DevicesChannelCategory.flow]: {
		required: [DevicesChannelPropertyCategory.rate],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.heater]: {
		required: [DevicesChannelPropertyCategory.temperature, DevicesChannelPropertyCategory.status],
		optional: [],
	},
	[DevicesChannelCategory.humidity]: {
		required: [DevicesChannelPropertyCategory.humidity],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.illuminance]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
		],
	},
	[DevicesChannelCategory.leak]: {
		required: [DevicesChannelPropertyCategory.detected],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault, DevicesChannelPropertyCategory.tampered],
	},
	[DevicesChannelCategory.light]: {
		required: [DevicesChannelPropertyCategory.on],
		optional: [
			DevicesChannelPropertyCategory.brightness,
			DevicesChannelPropertyCategory.color_red,
			DevicesChannelPropertyCategory.color_green,
			DevicesChannelPropertyCategory.color_blue,
			DevicesChannelPropertyCategory.color_white,
			DevicesChannelPropertyCategory.color_temperature,
			DevicesChannelPropertyCategory.hue,
			DevicesChannelPropertyCategory.saturation,
		],
	},
	[DevicesChannelCategory.lock]: {
		required: [DevicesChannelPropertyCategory.on, DevicesChannelPropertyCategory.status],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault, DevicesChannelPropertyCategory.tampered],
	},
	[DevicesChannelCategory.media_input]: {
		required: [],
		optional: [],
	},
	[DevicesChannelCategory.media_playback]: {
		required: [],
		optional: [],
	},
	[DevicesChannelCategory.microphone]: {
		required: [DevicesChannelPropertyCategory.active],
		optional: [DevicesChannelPropertyCategory.volume],
	},
	[DevicesChannelCategory.motion]: {
		required: [DevicesChannelPropertyCategory.detected],
		optional: [
			DevicesChannelPropertyCategory.distance,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.nitrogen_dioxide]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.mode,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.occupancy]: {
		required: [DevicesChannelPropertyCategory.detected],
		optional: [
			DevicesChannelPropertyCategory.distance,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.outlet]: {
		required: [DevicesChannelPropertyCategory.on],
		optional: [DevicesChannelPropertyCategory.in_use],
	},
	[DevicesChannelCategory.ozone]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.pressure]: {
		required: [DevicesChannelPropertyCategory.measured],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.robot_vacuum]: {
		required: [DevicesChannelPropertyCategory.on, DevicesChannelPropertyCategory.status],
		optional: [DevicesChannelPropertyCategory.mode, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.smoke]: {
		required: [DevicesChannelPropertyCategory.detected],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault, DevicesChannelPropertyCategory.tampered],
	},
	[DevicesChannelCategory.speaker]: {
		required: [DevicesChannelPropertyCategory.active],
		optional: [DevicesChannelPropertyCategory.volume, DevicesChannelPropertyCategory.mode],
	},
	[DevicesChannelCategory.sulphur_dioxide]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.switcher]: {
		required: [DevicesChannelPropertyCategory.on],
		optional: [],
	},
	[DevicesChannelCategory.television]: {
		required: [DevicesChannelPropertyCategory.on, DevicesChannelPropertyCategory.brightness, DevicesChannelPropertyCategory.input_source],
		optional: [DevicesChannelPropertyCategory.remote_key],
	},
	[DevicesChannelCategory.temperature]: {
		required: [DevicesChannelPropertyCategory.temperature],
		optional: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.fault],
	},
	[DevicesChannelCategory.thermostat]: {
		required: [DevicesChannelPropertyCategory.active, DevicesChannelPropertyCategory.mode],
		optional: [DevicesChannelPropertyCategory.locked, DevicesChannelPropertyCategory.units],
	},
	[DevicesChannelCategory.valve]: {
		required: [DevicesChannelPropertyCategory.on, DevicesChannelPropertyCategory.type],
		optional: [
			DevicesChannelPropertyCategory.duration,
			DevicesChannelPropertyCategory.remaining,
			DevicesChannelPropertyCategory.mode,
			DevicesChannelPropertyCategory.fault,
		],
	},
	[DevicesChannelCategory.volatile_organic_compounds]: {
		required: [],
		optional: [
			DevicesChannelPropertyCategory.detected,
			DevicesChannelPropertyCategory.density,
			DevicesChannelPropertyCategory.level,
			DevicesChannelPropertyCategory.active,
			DevicesChannelPropertyCategory.fault,
			DevicesChannelPropertyCategory.tampered,
		],
	},
	[DevicesChannelCategory.window_covering]: {
		required: [
			DevicesChannelPropertyCategory.obstruction,
			DevicesChannelPropertyCategory.status,
			DevicesChannelPropertyCategory.position,
			DevicesChannelPropertyCategory.type,
		],
		optional: [DevicesChannelPropertyCategory.percentage, DevicesChannelPropertyCategory.tilt, DevicesChannelPropertyCategory.fault],
	},
};
