/**
 * OpenAPI extra models for Spaces module
 */
import { BulkAssignDto, ReqBulkAssignDto } from './dto/bulk-assign.dto';
import { ClimateIntentDto, ReqClimateIntentDto } from './dto/climate-intent.dto';
import {
	BulkSetClimateRolesDto,
	ReqBulkSetClimateRolesDto,
	ReqSetClimateRoleDto,
	SetClimateRoleDto,
} from './dto/climate-role.dto';
import { CoversIntentDto, ReqCoversIntentDto } from './dto/covers-intent.dto';
import {
	BulkSetCoversRolesDto,
	ReqBulkSetCoversRolesDto,
	ReqSetCoversRoleDto,
	SetCoversRoleDto,
} from './dto/covers-role.dto';
import { CreateSpaceDto, ReqCreateSpaceDto } from './dto/create-space.dto';
import { LightingIntentDto, ReqLightingIntentDto } from './dto/lighting-intent.dto';
import {
	BulkSetLightingRolesDto,
	ReqBulkSetLightingRolesDto,
	ReqSetLightingRoleDto,
	SetLightingRoleDto,
} from './dto/lighting-role.dto';
import { ReqSuggestionFeedbackDto, SuggestionFeedbackDto } from './dto/suggestion.dto';
import { ReqUpdateSpaceDto, UpdateSpaceDto } from './dto/update-space.dto';
import { SpaceClimateRoleEntity } from './entities/space-climate-role.entity';
import { SpaceCoversRoleEntity } from './entities/space-covers-role.entity';
import { SpaceLightingRoleEntity } from './entities/space-lighting-role.entity';
import { SpaceEntity } from './entities/space.entity';
import {
	BulkAssignmentDataModel,
	BulkAssignmentResponseModel,
	BulkAssignmentResultDataModel,
	BulkClimateRoleResultItemModel,
	BulkClimateRolesResponseModel,
	BulkClimateRolesResultDataModel,
	BulkCoversRoleResultItemModel,
	BulkCoversRolesResponseModel,
	BulkCoversRolesResultDataModel,
	BulkLightingRolesResponseModel,
	BulkLightingRolesResultDataModel,
	CategoryTemplateDataModel,
	CategoryTemplatesResponseModel,
	ClimateIntentResponseModel,
	ClimateIntentResultDataModel,
	ClimateRoleResponseModel,
	ClimateStateDataModel,
	ClimateStateResponseModel,
	ClimateTargetDataModel,
	ClimateTargetsResponseModel,
	ContextSnapshotDataModel,
	ContextSnapshotResponseModel,
	CoversIntentResponseModel,
	CoversIntentResultDataModel,
	CoversRoleResponseModel,
	CoversStateDataModel,
	CoversStateResponseModel,
	CoversTargetDataModel,
	CoversTargetsResponseModel,
	IntentCatalogDataModel,
	IntentCatalogResponseModel,
	IntentCategoryDataModel,
	IntentEnumValueDataModel,
	IntentParamDataModel,
	IntentTypeDataModel,
	LightStateSnapshotDataModel,
	LightTargetDataModel,
	LightTargetsResponseModel,
	LightingContextDataModel,
	LightingIntentResponseModel,
	LightingIntentResultDataModel,
	LightingRoleMetaDataModel,
	LightingRoleResponseModel,
	LightingRolesResponseModel,
	LightingSummaryDataModel,
	ProposedSpaceDataModel,
	ProposedSpacesResponseModel,
	QuickActionDataModel,
	SpaceResponseModel,
	SpacesResponseModel,
	SuggestionDataModel,
	SuggestionFeedbackResponseModel,
	SuggestionFeedbackResultDataModel,
	SuggestionResponseModel,
	UndoResultDataModel,
	UndoResultResponseModel,
	UndoStateDataModel,
	UndoStateResponseModel,
} from './models/spaces-response.model';

export const SPACES_SWAGGER_EXTRA_MODELS = [
	// DTOs
	CreateSpaceDto,
	ReqCreateSpaceDto,
	UpdateSpaceDto,
	ReqUpdateSpaceDto,
	BulkAssignDto,
	ReqBulkAssignDto,
	LightingIntentDto,
	ReqLightingIntentDto,
	ClimateIntentDto,
	ReqClimateIntentDto,
	SetLightingRoleDto,
	ReqSetLightingRoleDto,
	BulkSetLightingRolesDto,
	ReqBulkSetLightingRolesDto,
	SetClimateRoleDto,
	ReqSetClimateRoleDto,
	BulkSetClimateRolesDto,
	ReqBulkSetClimateRolesDto,
	CoversIntentDto,
	ReqCoversIntentDto,
	SetCoversRoleDto,
	ReqSetCoversRoleDto,
	BulkSetCoversRolesDto,
	ReqBulkSetCoversRolesDto,
	SuggestionFeedbackDto,
	ReqSuggestionFeedbackDto,
	// Response models
	SpaceResponseModel,
	SpacesResponseModel,
	BulkAssignmentDataModel,
	BulkAssignmentResultDataModel,
	BulkAssignmentResponseModel,
	ProposedSpaceDataModel,
	ProposedSpacesResponseModel,
	LightingIntentResultDataModel,
	LightingIntentResponseModel,
	ClimateStateDataModel,
	ClimateStateResponseModel,
	ClimateIntentResultDataModel,
	ClimateIntentResponseModel,
	LightTargetDataModel,
	LightTargetsResponseModel,
	LightingRoleResponseModel,
	LightingRolesResponseModel,
	BulkLightingRolesResultDataModel,
	BulkLightingRolesResponseModel,
	ClimateTargetDataModel,
	ClimateTargetsResponseModel,
	ClimateRoleResponseModel,
	BulkClimateRoleResultItemModel,
	BulkClimateRolesResultDataModel,
	BulkClimateRolesResponseModel,
	// Covers response models
	CoversStateDataModel,
	CoversStateResponseModel,
	CoversIntentResultDataModel,
	CoversIntentResponseModel,
	CoversTargetDataModel,
	CoversTargetsResponseModel,
	CoversRoleResponseModel,
	BulkCoversRoleResultItemModel,
	BulkCoversRolesResultDataModel,
	BulkCoversRolesResponseModel,
	SuggestionDataModel,
	SuggestionResponseModel,
	SuggestionFeedbackResultDataModel,
	SuggestionFeedbackResponseModel,
	CategoryTemplateDataModel,
	CategoryTemplatesResponseModel,
	// Intent Catalog models
	IntentEnumValueDataModel,
	IntentParamDataModel,
	IntentTypeDataModel,
	IntentCategoryDataModel,
	QuickActionDataModel,
	LightingRoleMetaDataModel,
	IntentCatalogDataModel,
	IntentCatalogResponseModel,
	// Context Snapshot models
	LightStateSnapshotDataModel,
	LightingSummaryDataModel,
	LightingContextDataModel,
	ContextSnapshotDataModel,
	ContextSnapshotResponseModel,
	// Undo History models
	UndoStateDataModel,
	UndoStateResponseModel,
	UndoResultDataModel,
	UndoResultResponseModel,
	// Entities
	SpaceEntity,
	SpaceLightingRoleEntity,
	SpaceClimateRoleEntity,
	SpaceCoversRoleEntity,
];
