/**
 * OpenAPI extra models for Spaces module
 */
import { BulkAssignDto, ReqBulkAssignDto } from './dto/bulk-assign.dto';
import { ClimateIntentDto, ReqClimateIntentDto } from './dto/climate-intent.dto';
import {
	BulkSetClimateRolesDto,
	ReqBulkSetClimateRolesDto,
	ReqSetClimateRoleDto,
	SetClimateRoleDto,
} from './dto/climate-role.dto';
import { CoversIntentDto, ReqCoversIntentDto } from './dto/covers-intent.dto';
import {
	BulkSetCoversRolesDto,
	ReqBulkSetCoversRolesDto,
	ReqSetCoversRoleDto,
	SetCoversRoleDto,
} from './dto/covers-role.dto';
import { CreateSpaceDto, ReqCreateSpaceDto } from './dto/create-space.dto';
import { LightingIntentDto, ReqLightingIntentDto } from './dto/lighting-intent.dto';
import {
	BulkSetLightingRolesDto,
	ReqBulkSetLightingRolesDto,
	ReqSetLightingRoleDto,
	SetLightingRoleDto,
} from './dto/lighting-role.dto';
import { MediaIntentDto, ReqMediaIntentDto } from './dto/media-intent.dto';
import {
	BulkSetMediaRolesDto,
	ReqBulkSetMediaRolesDto,
	ReqSetMediaRoleDto,
	SetMediaRoleDto,
} from './dto/media-role.dto';
import {
	BulkSetSensorRolesDto,
	ReqBulkSetSensorRolesDto,
	ReqSetSensorRoleDto,
	SetSensorRoleDto,
} from './dto/sensor-role.dto';
import { ReqSuggestionFeedbackDto, SuggestionFeedbackDto } from './dto/suggestion.dto';
import { ReqUpdateSpaceDto, UpdateSpaceDto } from './dto/update-space.dto';
import { SpaceClimateRoleEntity } from './entities/space-climate-role.entity';
import { SpaceCoversRoleEntity } from './entities/space-covers-role.entity';
import { SpaceLightingRoleEntity } from './entities/space-lighting-role.entity';
import { SpaceMediaRoleEntity } from './entities/space-media-role.entity';
import { SpaceSensorRoleEntity } from './entities/space-sensor-role.entity';
import { SpaceEntity } from './entities/space.entity';
import {
	BulkAssignmentDataModel,
	BulkAssignmentResponseModel,
	BulkAssignmentResultDataModel,
	BulkClimateRoleResultItemModel,
	BulkClimateRolesResponseModel,
	BulkClimateRolesResultDataModel,
	BulkCoversRoleResultItemModel,
	BulkCoversRolesResponseModel,
	BulkCoversRolesResultDataModel,
	BulkLightingRolesResponseModel,
	BulkLightingRolesResultDataModel,
	BulkMediaRoleResultItemModel,
	BulkMediaRolesResponseModel,
	BulkMediaRolesResultDataModel,
	BulkSensorRoleResultItemModel,
	BulkSensorRolesResponseModel,
	BulkSensorRolesResultDataModel,
	CategoryTemplateDataModel,
	CategoryTemplatesResponseModel,
	ClimateIntentResponseModel,
	ClimateIntentResultDataModel,
	ClimateRoleResponseModel,
	ClimateStateDataModel,
	ClimateStateResponseModel,
	ClimateTargetDataModel,
	ClimateTargetsResponseModel,
	ContextSnapshotDataModel,
	ContextSnapshotResponseModel,
	CoversIntentResponseModel,
	CoversIntentResultDataModel,
	CoversRoleResponseModel,
	CoversStateDataModel,
	CoversStateResponseModel,
	CoversTargetDataModel,
	CoversTargetsResponseModel,
	EnvironmentSummaryDataModel,
	IntentCatalogDataModel,
	IntentCatalogResponseModel,
	IntentCategoryDataModel,
	IntentEnumValueDataModel,
	IntentParamDataModel,
	IntentTypeDataModel,
	LightStateSnapshotDataModel,
	LightTargetDataModel,
	LightTargetsResponseModel,
	LightingContextDataModel,
	LightingIntentResponseModel,
	LightingIntentResultDataModel,
	LightingRoleMetaDataModel,
	LightingRoleResponseModel,
	LightingRolesResponseModel,
	LightingSummaryDataModel,
	MediaIntentResponseModel,
	MediaIntentResultDataModel,
	MediaRoleResponseModel,
	// Media response models
	MediaStateDataModel,
	MediaStateResponseModel,
	MediaTargetDataModel,
	MediaTargetsResponseModel,
	ProposedSpaceDataModel,
	ProposedSpacesResponseModel,
	QuickActionDataModel,
	SafetyAlertDataModel,
	SensorReadingDataModel,
	SensorRoleReadingsDataModel,
	SensorRoleResponseModel,
	// Sensor response models
	SensorStateDataModel,
	SensorStateResponseModel,
	SensorTargetDataModel,
	SensorTargetsResponseModel,
	SpaceResponseModel,
	SpacesResponseModel,
	SuggestionDataModel,
	SuggestionFeedbackResponseModel,
	SuggestionFeedbackResultDataModel,
	SuggestionResponseModel,
	UndoResultDataModel,
	UndoResultResponseModel,
	UndoStateDataModel,
	UndoStateResponseModel,
} from './models/spaces-response.model';

export const SPACES_SWAGGER_EXTRA_MODELS = [
	// DTOs
	CreateSpaceDto,
	ReqCreateSpaceDto,
	UpdateSpaceDto,
	ReqUpdateSpaceDto,
	BulkAssignDto,
	ReqBulkAssignDto,
	LightingIntentDto,
	ReqLightingIntentDto,
	ClimateIntentDto,
	ReqClimateIntentDto,
	SetLightingRoleDto,
	ReqSetLightingRoleDto,
	BulkSetLightingRolesDto,
	ReqBulkSetLightingRolesDto,
	SetClimateRoleDto,
	ReqSetClimateRoleDto,
	BulkSetClimateRolesDto,
	ReqBulkSetClimateRolesDto,
	CoversIntentDto,
	ReqCoversIntentDto,
	SetCoversRoleDto,
	ReqSetCoversRoleDto,
	BulkSetCoversRolesDto,
	ReqBulkSetCoversRolesDto,
	MediaIntentDto,
	ReqMediaIntentDto,
	SetMediaRoleDto,
	ReqSetMediaRoleDto,
	BulkSetMediaRolesDto,
	ReqBulkSetMediaRolesDto,
	SuggestionFeedbackDto,
	ReqSuggestionFeedbackDto,
	// Sensor DTOs
	SetSensorRoleDto,
	ReqSetSensorRoleDto,
	BulkSetSensorRolesDto,
	ReqBulkSetSensorRolesDto,
	// Response models
	SpaceResponseModel,
	SpacesResponseModel,
	BulkAssignmentDataModel,
	BulkAssignmentResultDataModel,
	BulkAssignmentResponseModel,
	ProposedSpaceDataModel,
	ProposedSpacesResponseModel,
	LightingIntentResultDataModel,
	LightingIntentResponseModel,
	ClimateStateDataModel,
	ClimateStateResponseModel,
	ClimateIntentResultDataModel,
	ClimateIntentResponseModel,
	LightTargetDataModel,
	LightTargetsResponseModel,
	LightingRoleResponseModel,
	LightingRolesResponseModel,
	BulkLightingRolesResultDataModel,
	BulkLightingRolesResponseModel,
	ClimateTargetDataModel,
	ClimateTargetsResponseModel,
	ClimateRoleResponseModel,
	BulkClimateRoleResultItemModel,
	BulkClimateRolesResultDataModel,
	BulkClimateRolesResponseModel,
	// Covers response models
	CoversStateDataModel,
	CoversStateResponseModel,
	CoversIntentResultDataModel,
	CoversIntentResponseModel,
	CoversTargetDataModel,
	CoversTargetsResponseModel,
	CoversRoleResponseModel,
	BulkCoversRoleResultItemModel,
	BulkCoversRolesResultDataModel,
	BulkCoversRolesResponseModel,
	// Media response models
	MediaStateDataModel,
	MediaStateResponseModel,
	MediaIntentResultDataModel,
	MediaIntentResponseModel,
	MediaTargetDataModel,
	MediaTargetsResponseModel,
	MediaRoleResponseModel,
	BulkMediaRoleResultItemModel,
	BulkMediaRolesResultDataModel,
	BulkMediaRolesResponseModel,
	// Sensor response models
	SensorStateDataModel,
	SensorStateResponseModel,
	SensorTargetDataModel,
	SensorTargetsResponseModel,
	SensorRoleResponseModel,
	BulkSensorRoleResultItemModel,
	BulkSensorRolesResultDataModel,
	BulkSensorRolesResponseModel,
	SensorReadingDataModel,
	SensorRoleReadingsDataModel,
	EnvironmentSummaryDataModel,
	SafetyAlertDataModel,
	SuggestionDataModel,
	SuggestionResponseModel,
	SuggestionFeedbackResultDataModel,
	SuggestionFeedbackResponseModel,
	CategoryTemplateDataModel,
	CategoryTemplatesResponseModel,
	// Intent Catalog models
	IntentEnumValueDataModel,
	IntentParamDataModel,
	IntentTypeDataModel,
	IntentCategoryDataModel,
	QuickActionDataModel,
	LightingRoleMetaDataModel,
	IntentCatalogDataModel,
	IntentCatalogResponseModel,
	// Context Snapshot models
	LightStateSnapshotDataModel,
	LightingSummaryDataModel,
	LightingContextDataModel,
	ContextSnapshotDataModel,
	ContextSnapshotResponseModel,
	// Undo History models
	UndoStateDataModel,
	UndoStateResponseModel,
	UndoResultDataModel,
	UndoResultResponseModel,
	// Entities
	SpaceEntity,
	SpaceLightingRoleEntity,
	SpaceClimateRoleEntity,
	SpaceCoversRoleEntity,
	SpaceMediaRoleEntity,
	SpaceSensorRoleEntity,
];
