name: "Deploy Website"

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/website/**"
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-website"
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: "Build and deploy website to GitHub Pages"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        node-version: [ "24" ]
        pnpm-version: [ "10.12.0" ]
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Setup Node Project"
        uses: "./.github/actions/setup-node-project"
        with:
          node-version: "${{ matrix.node-version }}"
          pnpm-version: "${{ matrix.pnpm-version }}"

      - name: "Generate documentation"
        run: 'pnpm --filter @fastybird/smart-panel-website run generate:docs'

      - name: "Build"
        shell: "bash"
        run: 'pnpm --filter @fastybird/smart-panel-website build'

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v4"
        with:
          path: './apps/website/out'

      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
