name: PR Labeler

on:
  pull_request: # required for auto labeler
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  pr_labeler:
    name: "PR Labeler Bot"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Label"
        uses: "TimonVS/pr-labeler-action@v5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
