name: "Release Drafter"

on:
  push:
    branches:
      - "main"
  pull_request: # required for autolabeler
    branches:
      - "main"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "ready_for_review"
      - "review_requested"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-release:
    name: "Draft new release"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Draft new release"
        uses: "release-drafter/release-drafter@v6"
        with:
          config-name: ".github/release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
