name: "Website Publisher"

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    name: "Build web and publish it to Github pages"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      matrix:
        node-version: [ "22" ]
        pnpm-version: [ "10.13.0" ]
        operating-system: [ "ubuntu-latest" ]

    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Node Project"
        uses: "./.github/actions/setup-node-project"
        with:
          node-version: "${{ matrix.node-version }}"
          pnpm-version: "${{ matrix.pnpm-version }}"

      - name: "Build"
        shell: "bash"
        run: 'pnpm --filter @fastybird/smart-panel-docs build'

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: './docs/out'

      - name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
